name: Sync Database to Google Cloud Storage

on:
  workflow_run:
    workflows: ["Update Treasury Yields (Simplified)"]
    types:
      - completed
  workflow_dispatch:  # Allow manual trigger

jobs:
  sync-to-gcs:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        # Alternative: Use Workload Identity Federation
        # workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        # service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: future-footing-414610
    
    - name: Upload database to GCS
      run: |
        # Upload the main database
        gsutil -h "Content-Type:application/x-sqlite3" \
          cp google_analysis10/bonds_data.db \
          gs://json-receiver-databases/bonds_data.db
        
        # Create a timestamped backup
        BACKUP_NAME="bonds_data_$(date +%Y%m%d_%H%M%S).db"
        gsutil -h "Content-Type:application/x-sqlite3" \
          cp google_analysis10/bonds_data.db \
          "gs://json-receiver-databases/backups/${BACKUP_NAME}"
        
        echo "✅ Database synced to GCS" >> $GITHUB_STEP_SUMMARY
        echo "Main: gs://json-receiver-databases/bonds_data.db" >> $GITHUB_STEP_SUMMARY
        echo "Backup: gs://json-receiver-databases/backups/${BACKUP_NAME}" >> $GITHUB_STEP_SUMMARY
    
    - name: Verify upload
      run: |
        # Check file size in GCS
        gsutil du -h gs://json-receiver-databases/bonds_data.db
        
        # List recent backups
        echo "Recent backups:" >> $GITHUB_STEP_SUMMARY
        gsutil ls -l gs://json-receiver-databases/backups/ | tail -5 >> $GITHUB_STEP_SUMMARY